### PR TITLE
Updates to new Nette CSS and tests fixes

### PR DESCRIPTION
**Pull request by milo**

### CODE REVIEW

**Comment by milo** [comment]
Screenshot of logged in user.

ps_15-06-22

**Comment by Vrtak-CZ** [comment]
Thanks! I look at it as soon as possible.

**Comment by milo** [comment]
Great. I'm not sure about the Sign Up/In/Out and User buttons. Maybe [forum](http://forum.nette.org/en/) style is better, but in this case I have to ask DG to update CSS. Let me know after review.

**Comment by f3l1x** [comment]
Great! :+1:

**Comment by milo** [comment]
Ping @Vrtak-CZ

**Comment by milo** [comment]
Thank you @JanTvrdik, deployed.

**Pull request merged**
